allowBuilds:
  '@taufik-nurrohman/color-picker': true
  canvas: true
  dprint: true
  electron-winstaller: true
  esbuild: true
  sharp: true
  workerd: true
ignoreWorkspaceRootCheck: true
minimumReleaseAge: 10080
packages:
  - server/
  - shared/
  - client/
  - bot/
  - tests/
  - '!**dist/**'
shellEmulator: true
confirmModulesPurge: false
